Repository boostcamp-2020/IssueTracker-10, pull requests merged in 2020-10, with the labels that each got.

#14 feat: create issue controllers & layout (#6)
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Issue/IssueCreate/IssueCreateViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueNavigationViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueViewController.swift
Labels: iOS

#20 [feat/outh#1] Github Oauth login & signup
  .prettierrc.json
  server/.env-template
  server/app.js
  server/controllers/auth.js
  server/controllers/index.js
  server/middlewares/index.js
  server/middlewares/passport.js
  server/models/index.js
  server/models/user.js
  server/package-lock.json
  server/package.json
Labels: backend, web

#22 [feat/jwt#21] jwt middleware 추가
  server/controllers/auth.js
  server/middlewares/authenticateJwt.js
  server/middlewares/passport.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/utils/auth.js
Labels: backend, web

#26 [Feat/issueviewlayout#10] issue search viewController + filter logic
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Assets.xcassets/GithubMainColor.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Issue/FilterCancelView.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueCreate/IssueCreateViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Criteria.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/View/IssueCollectionViewCell.swift
Labels: iOS

#23 [feat/allIssue#2] Get all info api
  server/app.js
  server/controllers/api/index.js
  server/models/issue.js
  server/models/label.js
  server/models/milestone.js
  server/models/user.js
  server/services/errorMessages.js
  server/services/index.js
  server/services/successMessages.js
Labels: backend, web

#25 [Feat/select issue#2] Implement get issue info api
  server/controllers/auth.js
  server/controllers/issue.js
  server/middlewares/passport.js
  server/models/comment.js
  server/models/database/index.js
  server/models/issue.js
  server/services/issue.js
Labels: backend, web

#29 [Feat/create issue#2] 새로운 Issue를 생성하는 API 구현 + 테스트
  .eslintignore
  server/controllers/api/index.js
  server/controllers/api/issue.js
  server/controllers/auth.js
  server/controllers/index.js
  server/middlewares/authenticateJwt.js
  server/middlewares/passport.js
  server/models/comment.js
  server/models/config/sequelize.js
  server/models/database/index.js
  server/models/issue.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/services/issue.js
  server/test/issue.spec.js
Labels: web

#33 [feat/deleteIssue#2] delete issue api
  server/controllers/api/issue.js
  server/models/database/index.js
  server/models/issue.js
  server/services/issue.js
  server/services/successMessages.js
Labels: backend, web

#32 [Feat/change state#2] toggle state API 구현
  server/controllers/api/issue.js
  server/middlewares/authenticateJwt.js
  server/models/issue.js
  server/services/errorMessages.js
  server/services/issue.js
  server/services/successMessages.js
  server/test/toggleIssue.spec.js
Labels: web

#34 [Feat/update issue#2] update issue title api
  server/controllers/api/issue.js
  server/models/issue.js
  server/services/errorMessages.js
  server/services/issue.js
  server/services/successMessages.js
  server/test/issue.update.spec.js
Labels: backend, web

#43 [Fix#40] Fix issue api mismatch
  server/models/database/index.js
  server/models/issue.js
  server/services/errorMessages.js
  server/services/issue.js
Labels: backend, bug, web

#46 [bug/#45] open count와 close count bug 해결
  server/services/index.js
Labels: backend, bug, web
