Repository boostcamp-2020/IssueTracker-10, pull requests merged in 2020-11, with the labels that each got.

#54 [feat/deleteMilestone#3] Add delete milestone api
  server/controllers/api/index.js
  server/controllers/api/milestone.js
  server/models/milestone.js
  server/services/errorMessages.js
  server/services/milestone.js
  server/services/successMessages.js
Labels: backend, web

#60 [feat/toggleMilestoneState#3] Add toggle state of milestone API
  server/controllers/api/milestone.js
  server/models/milestone.js
  server/services/errorMessages.js
  server/services/issue.js
  server/services/milestone.js
  server/services/successMessages.js
Labels: backend, web

#63 [Feat/create milestone#3] create milestone api 구현
  server/controllers/api/milestone.js
  server/models/milestone.js
  server/services/errorMessages.js
  server/services/issue.js
  server/services/milestone.js
  server/services/successMessages.js
  server/test/milestone.create.spec.js
Labels: backend, web

#66 [Feat/update milestone#3] milestone update api 구현
  server/controllers/api/milestone.js
  server/models/milestone.js
  server/services/milestone.js
  server/test/milestone.update.spec.js
Labels: backend, web

#67 [feat/create label#4] Create label API
  server/controllers/api/index.js
  server/controllers/api/label.js
  server/models/label.js
  server/services/errorMessages.js
  server/services/label.js
  server/services/successMessages.js
Labels: backend, web

#68 [feat/getAllLabel#4] Get All label API
  server/controllers/api/label.js
  server/services/label.js
Labels: backend, web

#69 [Feat/delete#4] 레이블 삭제 API 구현
  server/controllers/api/label.js
  server/models/label.js
  server/services/errorMessages.js
  server/services/label.js
  server/services/successMessages.js
Labels: backend, web

#73 [feat/createComment#71] Add create comment API
  server/controllers/api/issue.js
  server/models/comment.js
  server/services/comment.js
  server/services/errorMessages.js
  server/services/successMessages.js
Labels: backend, web

#72 [Feat/update label#4] update label api 구현
  server/controllers/api/label.js
  server/models/label.js
  server/services/errorMessages.js
  server/services/label.js
  server/services/successMessages.js
  server/test/label.update.spec.js
Labels: backend, web

#74 [feat/getComment#71] Add get comment by issueId API
  server/controllers/api/issue.js
  server/models/comment.js
  server/services/comment.js
  server/services/successMessages.js
Labels: backend, web

#76 [Fix#61] select issue api 오류 수정
  server/models/issue.js
  server/services/issue.js
Labels: backend, bug, web

#79 [Feat/update comment#71] update comment api 구현
  server/controllers/api/comment.js
  server/controllers/api/index.js
  server/models/comment.js
  server/services/comment.js
  server/services/errorMessages.js
  server/services/successMessages.js
  server/test/comment.update.spec.js
Labels: backend, web

#80 [feat/deleteComment#71] Add delete comment API
  server/controllers/api/comment.js
  server/models/comment.js
  server/services/comment.js
  server/services/errorMessages.js
  server/services/successMessages.js
Labels: backend, web

#83 [Fix#82] milestone 목록 조회 오류 수정
  server/services/milestone.js
Labels: backend, bug, web

#88 [fix/#86] Get all info API 버그 수정
  server/services/index.js
Labels: backend, bug, web

#81 [Feat/apple login#52] Sign In With Apple
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Home/HomeViewController.swift
  iOS/IssueTracker/IssueTracker/IssueTracker.entitlements
  iOS/IssueTracker/IssueTracker/Profile/ProfileViewController.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/SignIn/KeychainItem.swift
  iOS/IssueTracker/IssueTracker/SignIn/SignIn.storyboard
  iOS/IssueTracker/IssueTracker/SignIn/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/SignIn/UIViewController+showLoginView.swift
  iOS/IssueTracker/IssueTracker/SignIn/User.swift
  iOS/IssueTracker/IssueTracker/Util/AppData.swift
  iOS/IssueTracker/IssueTracker/Util/Storage.swift
Labels: iOS

#100 [Feat/requestapi#99] API를 통해 데이터 fetch
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/CollectionHeaderView.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/CollectionHeaderView.xib
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/IssueDetailCell.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/IssueDetailCell.xib
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/IssueDetailCellHeader.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+CollectionViewDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+FlowLayout.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+SearchUpdate.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+UI.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/IssueFactory.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/IssueManager.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/IssueViewModel.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/View/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/View/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/View/LeftAlignLayout.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueViewModel.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueNavigationViewController.swift
Labels: iOS

#98 [Client/config#77] 클라이언트 환경설정
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/Components/Main.js
  client/src/Routes/index.js
  client/src/index.js
  client/src/theme.js
  client/webpack.config.js
Labels: environment ⚙️, frontend

#103 [fix/#96] Fix the order from ascending to descending
  server/models/issue.js
  server/models/label.js
  server/models/milestone.js
Labels: backend, bug, web

#102 [Feat/filter#85] issue list 필터 기능 추가
  server/models/issue.js
  server/services/issue.js
Labels: backend

#104 [Feat/update detail#93] 이슈 디테일 관계 갱신 api 구현
  server/controllers/api/issue.js
  server/models/issue.js
  server/services/issue.js
  server/test/issue.update.detail.spec.js
Labels: backend, web

#108 [Deploy] 백엔드 배포를 위한 머지
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/Components/Main.js
  client/src/Routes/index.js
  client/src/index.js
  client/src/theme.js
  client/webpack.config.js
  server/controllers/api/issue.js
  server/models/issue.js
  server/models/label.js
  server/models/milestone.js
  server/services/issue.js
  server/test/issue.update.detail.spec.js
Labels: prod server, web

#107 [Feat/login#106] context 추가 + 로그인 컴포넌트 생성
  client/.env-template
  client/package-lock.json
  client/package.json
  client/src/Api/index.js
  client/src/App.js
  client/src/Components/Login.js
  client/src/Components/Main.js
  client/src/Components/Provider/Auth.js
  client/src/Context/AuthContext.js
  client/src/Routes/index.js
  client/src/index.js
  client/src/theme.js
  client/webpack.config.js
Labels: frontend, web

#110 [Feat/filter#101] FilterView 기능 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Issue/FilterIssueNavigationViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/Filter.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/FilterDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/FilterTableViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/IssueFilterViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Criteria.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueViewModel.swift
Labels: iOS

#118 [feat/filterInput#112] Filter bar component
  client/src/Components/BoldText.js
  client/src/Components/FilterInput.js
  client/src/Components/FilterModal.js
  client/src/Components/Header.js
  client/src/Components/Icons.js
  client/src/Components/Input.js
  client/src/Components/Issue.js
  client/src/Components/Login.js
  client/src/Routes/index.js
  client/src/theme.js
Labels: frontend, web

#119 [Feat/button component#112] issue 페이지 버튼 컴포넌트 구현
  client/src/Components/GreenButton.js
  client/src/Components/IssueButtons.js
  client/src/Components/LabelButton.js
  client/src/Components/LabelMilestoneButton.js
  client/src/Components/MilestoneButton.js
  client/src/Components/icons.js
  client/src/theme.js
Labels: frontend, web

#120 [Feat/list#112] 메인 페이지 이슈목록 컴포넌트 구현
  client/src/Components/Issue.js
  client/src/Components/IssueFilterModal.js
  client/src/Components/IssueFilterRender.js
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListRow.js
  client/src/Components/Login.js
  client/src/Components/Main.js
  client/src/theme.js
  client/src/utils/convert.js
Labels: frontend, web

#117 [feat/Cancel#115] Cancel버튼 클릭시, 자동으로 모두 선택 해제하기
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+CollectionViewDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController.swift
Labels: iOS

#125 [Fix/svg] svg 오류
  client/src/Components/Icons.js
  client/src/Components/static/svgIcons.js
Labels: bug

#131 [Feat/main#130] 메인 페이지 컴포넌트 수정
  client/src/Api/index.js
  client/src/Components/FilterInput.js
  client/src/Components/FilterModal.js
  client/src/Components/GreenButton.js
  client/src/Components/Issue.js
  client/src/Components/IssueFilterRender.js
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListRow.js
  client/src/Components/LabelButton.js
  client/src/Components/LabelMilestoneButton.js
  client/src/Components/Login.js
  client/src/Components/Main.js
  client/src/Components/MilestoneButton.js
  client/src/Components/static/svgIcons.js
  client/src/Context/AuthContext.js
  client/src/theme.js
  client/src/utils/parse.js
  server/.env-template
  server/app.js
  server/controllers/auth.js
  server/middlewares/passport.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/services/auth.js
Labels: frontend

#128 [Deploy] 2주차 배포
  client/.env-template
  client/package-lock.json
  client/package.json
  client/src/Api/index.js
  client/src/App.js
  client/src/Components/BoldText.js
  client/src/Components/FilterInput.js
  client/src/Components/FilterModal.js
  client/src/Components/GreenButton.js
  client/src/Components/Header.js
  client/src/Components/Input.js
  client/src/Components/Issue.js
  client/src/Components/IssueButtons.js
  client/src/Components/IssueFilterModal.js
  client/src/Components/IssueFilterRender.js
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListRow.js
  client/src/Components/LabelButton.js
  client/src/Components/LabelMilestoneButton.js
  client/src/Components/Login.js
  client/src/Components/Main.js
  client/src/Components/MilestoneButton.js
  client/src/Components/Provider/Auth.js
  client/src/Components/static/svgIcons.js
  client/src/Context/AuthContext.js
  client/src/Routes/index.js
  client/src/index.js
  client/src/theme.js
  client/src/utils/convert.js
  client/src/utils/parse.js
  client/webpack.config.js
  server/.env-template
  server/app.js
  server/controllers/auth.js
  server/middlewares/passport.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/services/auth.js
Labels: prod server

#137 [deploy] 버그 수정 후 배포
  client/.env-template
  client/src/Api/index.js
  client/src/Components/Issue.js
  client/src/Context/AuthContext.js
  server/package-lock.json
  server/services/auth.js
Labels: prod server

#146 [Fix/token] 토큰 없이 데이터 가져오는 문제 수정
  client/src/Components/Issue.js
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListRow.js
  client/src/Components/Main.js
  client/src/Context/AuthContext.js
Labels: bug

#149 [Bug/#147] Fixed filter modal blocking checkbox problem
  client/src/Components/FilterInput.js
  client/src/Components/FilterModal.js
Labels: bug, frontend, web

#151 [bug/#147] Modal rendering zero value display problem
  client/src/Components/FilterInput.js
  client/src/Components/FilterModal.js
Labels: bug, frontend, web

#152 [Feat/row#148#112] row 체크박스 기능 + 아이콘 추가
  .eslintrc
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListRow.js
  client/src/Components/static/svgIcons.js
Labels: frontend, web

#154 [Refactor/issue list viewto unidirectional flow#145] 구조리팩토링
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Issue/FilterIssueNavigationViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+CollectionViewDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+FlowLayout.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+SearchUpdate.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+UI.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/IssueManager.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/SelectedLabels.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/View/IssueListViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/View/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueListReactor.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueListState.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueViewModel.swift
Labels: iOS

#144 [Feat/filter save#143] 필터 저장하기 + 이슈뷰 Select All
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+CollectionViewDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+UI.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/Filter.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/FilterDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/IssueFilterViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueListReactor.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueListState.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/ViewModel/IssueViewModel.swift
  iOS/IssueTracker/IssueTracker/SignIn/User.swift
  iOS/IssueTracker/IssueTracker/Util/AppData.swift
Labels: iOS

#157 [Feat/filter#153] filter 기능을 위해 context 추가 및 open/closed 이슈 렌더링
  client/src/App.js
  client/src/Components/Issue.js
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListHeaderText.js
  client/src/Components/Provider/Issue.js
  client/src/Components/static/svgIcons.js
  client/src/Context/IssueContext.js
Labels: frontend, web

#159 [Feat/new issue#156] 이슈 생성 페이지 구현
  client/src/Components/GreenButton.js
  client/src/Components/Issue.js
  client/src/Components/IssueSideBar.js
  client/src/Components/NewIssue.js
  client/src/Components/NewIssueInput.js
  client/src/Components/SideBarElement.js
  client/src/Components/static/svgIcons.js
  client/src/Routes/index.js
Labels: frontend, web

#160 [Feat/filter#153] 이슈 필터링 author & assignee 기능 구현
  client/src/Components/IssueFilterModal.js
  client/src/Components/IssueFilterRender.js
  client/src/Components/IssueListHeaderText.js
  client/src/Context/IssueContext.js
Labels: frontend, web

#161 [Feat/labelList#155] Read & Create Label
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Button.js
  client/src/Components/Label.js
  client/src/Components/LabelBadge.js
  client/src/Components/LabelCreateModal/LabelCreateModalContainer.js
  client/src/Components/LabelCreateModal/LabelCreateModalPresenter.js
  client/src/Components/LabelCreateModal/index.js
  client/src/Components/LabelFilter.js
  client/src/Components/LabelList.js
  client/src/Components/LabelListRow.js
  client/src/Components/Provider/Label.js
  client/src/Components/static/svgIcons.js
  client/src/Context/LabelContext.js
  client/src/Routes/index.js
  client/src/theme.js
  client/src/utils/color.js
Labels: frontend, web

#163 [Fix/tokentrue] token 변경
  client/src/Components/FilterInput.js
  client/src/Components/IssueFilterModal.js
  client/src/Components/IssueFilterRender.js
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListHeaderText.js
  client/src/Components/Main.js
Labels: bug, frontend

#168 [Feat/label view#7] LabelView
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Extensions/NotificationName.swift
  iOS/IssueTracker/IssueTracker/Home/HomeViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Label/LabelTableViewCell.swift
  iOS/IssueTracker/IssueTracker/Label/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Label/Model/Label.swift
  iOS/IssueTracker/IssueTracker/Label/Model/LabelManager.swift
  iOS/IssueTracker/IssueTracker/Label/PopupViewController.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelDataSource.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelReactor.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelState.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelViewModel.swift
Labels: iOS

#173 [Refactor] client code refactoring
  client/src/Components/Common/BoldText.js
  client/src/Components/Common/Button.js
  client/src/Components/Common/GreenButton.js
  client/src/Components/Common/Header.js
  client/src/Components/Common/Input.js
  client/src/Components/Common/LabelButton.js
  client/src/Components/Common/LabelMilestoneButton.js
  client/src/Components/Common/MilestoneButton.js
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/FilterModal.js
  client/src/Components/Issue/Issue.js
  client/src/Components/Issue/IssueButtons.js
  client/src/Components/Issue/IssueFilter/FilterInput.js
  client/src/Components/Issue/IssueFilter/IssueFilterModal.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Components/Issue/IssueList.js
  client/src/Components/Issue/IssueListHeader.js
  client/src/Components/Issue/IssueListHeaderText.js
  client/src/Components/Issue/IssueListRow.js
  client/src/Components/Issue/IssueSideBar.js
  client/src/Components/Issue/NewIssue.js
  client/src/Components/Issue/NewIssueInput.js
  client/src/Components/Issue/SideBarElement.js
  client/src/Components/Issue/SideBarList.js
  client/src/Components/Issue/SideBarModal.js
  client/src/Components/Label/Label.js
  client/src/Components/Label/LabelBadge.js
  client/src/Components/Label/LabelButton.js
  client/src/Components/Label/LabelCreateModal/LabelCreateModalContainer.js
  client/src/Components/Label/LabelCreateModal/LabelCreateModalPresenter.js
  client/src/Components/Label/LabelCreateModal/index.js
  client/src/Components/Label/LabelFilter.js
  client/src/Components/Label/LabelList.js
  client/src/Components/Label/LabelListRow.js
  client/src/Components/Main.js
  client/src/Routes/index.js
Labels: frontend 🎨, web

#174 Refactor: Code refactoring
  client/src/Components/BoldText.js
  client/src/Components/Button.js
  client/src/Components/CheckedList.js
  client/src/Components/FilterInput.js
  client/src/Components/FilterModal.js
  client/src/Components/GreenButton.js
  client/src/Components/Header.js
  client/src/Components/Input.js
  client/src/Components/Issue.js
  client/src/Components/IssueButtons.js
  client/src/Components/IssueFilterModal.js
  client/src/Components/IssueFilterRender.js
  client/src/Components/IssueList.js
  client/src/Components/IssueListHeader.js
  client/src/Components/IssueListHeaderText.js
  client/src/Components/IssueListRow.js
  client/src/Components/IssueSideBar.js
  client/src/Components/Label.js
  client/src/Components/LabelBadge.js
  client/src/Components/LabelButton.js
  client/src/Components/LabelCreateModal/LabelCreateModalContainer.js
  client/src/Components/LabelCreateModal/LabelCreateModalPresenter.js
  client/src/Components/LabelCreateModal/index.js
  client/src/Components/LabelFilter.js
  client/src/Components/LabelList.js
  client/src/Components/LabelListRow.js
  client/src/Components/LabelMilestoneButton.js
  client/src/Components/MilestoneButton.js
  client/src/Components/NewIssue.js
  client/src/Components/NewIssueInput.js
  client/src/Components/SideBarElement.js
  client/src/Components/SideBarList.js
  client/src/Components/SideBarModal.js
Labels: frontend 🎨, web

#177 [Feat/mark#148] issue 중복 선택 후 state 변경
  client/src/Components/Issue/Issue.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Components/Issue/IssueListHeader.js
  client/src/Context/IssueContext.js
Labels: frontend 🎨, web

#179 [Feat/label#178] row에 label 추가
  client/src/Components/Issue/IssueLabel.js
  client/src/Components/Issue/IssueListRow.js
Labels: frontend 🎨

#181 [Feat/select detail#156] 이슈 생성 시, 담당자, 라벨, 마일스톤 저장 기능 구현
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/IssueSideBar.js
  client/src/Components/Issue/NewIssueInput.js
  client/src/Components/Issue/SideBarElement.js
  client/src/Components/Issue/SideBarList.js
  client/src/Components/Issue/SideBarModal.js
Labels: frontend 🎨, web

#183 [Feat/login#170] 로그인 로직 완료
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Extensions/NotificationName.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/IssueDetailCellHeader.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/Filter.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Criteria.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/IssueManager.swift
  iOS/IssueTracker/IssueTracker/Label/Model/LabelManager.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/SignIn/SignInHelper.swift
  iOS/IssueTracker/IssueTracker/SignIn/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/SignIn/User.swift
  iOS/IssueTracker/IssueTracker/Util/AppData.swift
  iOS/IssueTracker/IssueTracker/Util/Environment.swift
Labels: 🍎 iOS 🍎

#182 [Feat/route#180] 이슈 타이틀 클릭 시 라우팅 및 웹팩 수정
  client/src/Components/Issue/IssueDetail/index.js
  client/src/Components/Issue/IssueListRow.js
  client/src/Routes/index.js
  client/webpack.config.js
Labels: environment ⚙️, frontend 🎨

#189 [Feat/toggle selected#156] 선택된 assignees, labels, milestone 선택 해제 기능 구현
  client/src/Components/Common/GreenButton.js
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/SideBarList.js
Labels: frontend 🎨, web

#192 [Fix/issue api#188] count를 issue API에서 가져오게 변경
  client/src/Components/Issue/Issue.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Context/IssueContext.js
  server/models/issue.js
  server/services/index.js
  server/services/issue.js
Labels: backend, bug 🤔, frontend 🎨

#194 Feat: Add label delete confirm modal
  client/src/Components/Label/LabelDeleteModal.js
  client/src/Components/Label/LabelListRow.js
Labels: frontend 🎨, web

#198 [Feat/get user info] assign yourself 버튼 기능 구현
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/NewIssue.js
  client/src/Components/Issue/NewIssueInput.js
  client/src/Context/AuthContext.js
  server/controllers/auth.js
  server/models/user.js
  server/services/auth.js
Labels: frontend 🎨, web

#195 [Feat/reset#153] 필터 리셋 컴포넌트 추가
  client/src/Components/Common/LabelMilestoneButton.js
  client/src/Components/Issue/Issue.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Components/Issue/IssueList.js
  client/src/Components/static/svgIcons.js
  client/src/Context/IssueContext.js
Labels: frontend 🎨

#200 [Feat/labelValidation#187] Add validation for create & update label
  client/src/Components/Common/Balloon.js
  client/src/Components/Common/Button.js
  client/src/Components/Common/Input.js
  client/src/Components/Label/LabelBadge.js
  client/src/Components/Label/LabelCreateModal/LabelCreateModalContainer.js
  client/src/Components/Label/LabelCreateModal/LabelCreateModalPresenter.js
  client/src/Components/Label/LabelUpdateModal/LabelUpdateModalContainer.js
  client/src/Components/Label/LabelUpdateModal/LabelUpdateModalPresenter.js
  client/src/theme.js
Labels: frontend 🎨, web

#203 [Fix/time#196] 시간 표기 오류
  client/src/utils/convert.js
Labels: bug 🤔

#193 [Feat/login view#50] Login View + Profile View
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/100.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/1024.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/114.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/120.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/144.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/152.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/167.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/180.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/20.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/29.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/40.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/50.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/57.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/58.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/60.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/72.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/76.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/80.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/87.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Controller/IssueViewController+UI.swift
  iOS/IssueTracker/IssueTracker/Label/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelViewModel.swift
  iOS/IssueTracker/IssueTracker/Profile/ProfileViewController.swift
  iOS/IssueTracker/IssueTracker/SignIn/SignIn.storyboard
  iOS/IssueTracker/IssueTracker/SignIn/SignInViewController.swift
Labels: 🍎 iOS 🍎

#205 [Feat/progress bar#199] 선택된 마일스톤 진행도 그리기 구현
  client/src/App.js
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/NewIssue.js
  client/src/Components/Issue/NewIssueInput.js
  client/src/Components/Issue/SideBarList.js
  client/src/Components/Provider/Milestone.js
  client/src/Context/MilestoneContext.js
  server/models/milestone.js
Labels: frontend 🎨, web

#209 [bug/#197] Fix bug infinite increasing label bug
  client/src/Context/LabelContext.js
Labels: bug 🤔, frontend 🎨, web

#210 [Feat/comment create#58] 커멘트 생성 및 이미지 캐시
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Comment/Controller/CommentCreateViewController.swift
  iOS/IssueTracker/IssueTracker/Comment/Controller/CommentNavigationViewController.swift
  iOS/IssueTracker/IssueTracker/Comment/Model/CommentManager.swift
  iOS/IssueTracker/IssueTracker/Comment/ViewModel/CommentCreateReactor.swift
  iOS/IssueTracker/IssueTracker/Comment/ViewModel/CommentCreateState.swift
  iOS/IssueTracker/IssueTracker/Comment/ViewModel/CommentCreateViewModel.swift
  iOS/IssueTracker/IssueTracker/Extensions/NotificationName.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/Contoroller/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/IssueDetailCellHeader.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/StateView.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/ViewModel/IssueDetailViewModel.swift
  iOS/IssueTracker/IssueTracker/Profile/ProfileViewController.swift
  iOS/IssueTracker/IssueTracker/Util/ImageCache.swift
Labels: 🍎 iOS 🍎

#211 [Feat/label#153] label, milestone 필터링 기능 추가
  client/src/Components/Issue/Issue.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Context/IssueContext.js
  client/src/utils/convert.js
  server/models/issue.js
Labels: backend, frontend 🎨

#213 [Feat/upload file#204] 파일 업로드 기능 구현
  .gitignore
  client/src/Api/index.js
  client/src/Components/Issue/InputComment.js
  client/src/Components/Issue/NewIssueInput.js
  client/src/theme.js
  server/.env-template
  server/controllers/api/index.js
  server/package-lock.json
  server/package.json
  server/services/file.js
Labels: backend, frontend 🎨, web

#214 [Feat/filter#190] Add label title search page
  client/src/Components/Common/LabelMilestoneButton.js
  client/src/Components/Label/LabelFilter.js
  client/src/Components/Label/LabelList.js
  client/src/Components/Label/Search.js
  client/src/Components/static/svgIcons.js
  client/src/Routes/index.js
Labels: frontend 🎨, web

#215 [Feat/link detail#156] 이슈 생성 후, 이슈 디테일 페이지로 이동 기능 구현
  client/src/Components/Issue/Issue.js
  client/src/Components/Issue/NewIssue.js
  client/src/Components/Issue/NewIssueInput.js
  client/src/Routes/index.js
  server/services/issue.js
Labels: frontend 🎨, web

#219 [Feat/header#180] issue detail 헤더 구현
  client/src/Components/Issue/IssueDetail/IssueDetailHeader.js
  client/src/Components/Issue/IssueDetail/index.js
  server/models/issue.js
Labels: frontend 🎨, web

#223 [Feat/milestoneList#217] Milestone을 조회하는 component 추가
  client/src/Components/Common/ProgressBar.js
  client/src/Components/Milestone/Milestone.js
  client/src/Components/Milestone/MilestoneCreate.js
  client/src/Components/Milestone/MilestoneList.js
  client/src/Components/Milestone/MilestoneListRow.js
  client/src/Components/static/svgIcons.js
  client/src/Routes/index.js
  client/src/utils/getPercent.js
  server/models/milestone.js
Labels: frontend 🎨, web

#222 [Fix/bug#216] 이슈 생성시, comment 생성 오류 수정
  client/src/Components/Issue/InputComment.js
Labels: bug 🤔, frontend 🎨, web

#229 [Feat/createMilestone] Milestone을 생성하는 page 구현
  client/src/Components/Milestone/Milestone.js
  client/src/Components/Milestone/MilestoneCreate.js
  client/src/Components/Milestone/MilestoneCreate/MilestoneCreateContainer.js
  client/src/Components/Milestone/MilestoneCreate/MilestoneCreatePresenter.js
  client/src/Components/Milestone/MilestoneCreate/index.js
  client/src/Components/Milestone/MilestoneList.js
  client/src/Context/MilestoneContext.js
  server/services/milestone.js
Labels: frontend 🎨, web

#230 [Feat/display content length#226] content 길이 표시 기능 추가
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/InputComment.js
  client/src/Components/Issue/SideBarList.js
  client/src/utils/color.js
  client/src/utils/time.js
Labels: frontend 🎨, web

#227 [Feat/markup#180] comment 관련 컴포넌트 추가
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueDetail/IssueComment.js
  client/src/Components/Issue/IssueDetail/IssueDetailHeader.js
  client/src/Components/Issue/IssueDetail/index.js
  server/models/issue.js
Labels: frontend 🎨

#233 [Fix/auth#224] 라우터 기능 변경 + alias 추가
  .eslintrc
  client/babel.config.js
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/src/Api/index.js
  client/src/Components/Issue/Issue.js
  client/src/Components/Login.js
  client/src/Context/AuthContext.js
  client/src/Routes/Authenticated.js
  client/src/Routes/index.js
  package-lock.json
  package.json
Labels: bug 🤔, frontend 🎨, refactoring 🙌

#235 [Fix/comment#225] issue-comment 필수 관계로 수정
  server/models/database/index.js
Labels: bug 🤔

#234 [Feat/detailpage#180] 이슈 디테일 페이지 사이드바 추가
  client/src/App.js
  client/src/Components/Issue/InputComment.js
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueDetail/IssueDetailHeader.js
  client/src/Components/Issue/IssueDetail/index.js
  client/src/Components/Issue/NewIssue.js
  client/src/Components/Issue/SideBarList.js
  client/src/Context/IssueInfoContext.js
  server/services/issue.js
Labels: frontend 🎨, web

#242 [Feat/edit#220] Milestone을 수정하고 삭제하는 기능 추가
  client/src/Components/Milestone/MilestoneEdit/MilestoneUpdateContainer.js
  client/src/Components/Milestone/MilestoneEdit/MilestoneUpdatePresenter.js
  client/src/Components/Milestone/MilestoneEdit/index.js
  client/src/Components/Milestone/MilestoneListRow.js
  client/src/Context/MilestoneContext.js
  client/src/Routes/index.js
Labels: frontend 🎨, web

#246 [Bug/#244] Delete milestone bug
  client/src/Components/Milestone/MilestoneListRow.js
  client/src/Context/MilestoneContext.js
  client/src/Routes/index.js
  package-lock.json
Labels: bug 🤔, frontend 🎨, web

#240 [Style : add styling] CSS 수정
  client/src/Components/Common/BoldText.js
  client/src/Components/Common/Button.js
  client/src/Components/Common/Header.js
  client/src/Components/Common/LabelButton.js
  client/src/Components/Common/MilestoneButton.js
  client/src/Components/Label/Label.js
  client/src/Components/Label/LabelBadge.js
  client/src/Components/Label/LabelFilter.js
  client/src/Components/Label/LabelList.js
  client/src/Components/Label/LabelListRow.js
  client/src/Components/Main.js
Labels: frontend 🎨

#238 [Feat/mile stone#206] 마일스톤 뷰
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Extensions/NotificationName.swift
  iOS/IssueTracker/IssueTracker/Extensions/UIView+addExternalBorder.swift
  iOS/IssueTracker/IssueTracker/Home/HomeViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueList/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Label/LabelPopupViewController.swift
  iOS/IssueTracker/IssueTracker/Label/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Label/Model/LabelManager.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelDataSource.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelReactor.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelViewModel.swift
  iOS/IssueTracker/IssueTracker/MileStone/MileStoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/MileStone/MileStonePopUpViewController.swift
  iOS/IssueTracker/IssueTracker/MileStone/MileStoneViewController.swift
  iOS/IssueTracker/IssueTracker/MileStone/Model/MileStone.swift
  iOS/IssueTracker/IssueTracker/MileStone/Model/MileStoneManager.swift
  iOS/IssueTracker/IssueTracker/MileStone/ViewModel/MileStoneDataSource.swift
  iOS/IssueTracker/IssueTracker/MileStone/ViewModel/MileStoneReactor.swift
  iOS/IssueTracker/IssueTracker/MileStone/ViewModel/MileStoneState.swift
  iOS/IssueTracker/IssueTracker/MileStone/ViewModel/MileStoneViewModel.swift
  iOS/IssueTracker/IssueTracker/SignIn/SignInHelper.swift
Labels: 🍎 iOS 🍎

#249 [Bug/#231] Label 목록 폰트 색상 미적용 해결
  client/src/Components/Label/LabelListRow.js
  client/src/utils/color.js
Labels: bug 🤔, frontend 🎨, web

#243 [Feat/update issue detail#237] 생성된 이슈의 assignees, labels, milestone 변경 기능 추가
  client/src/Components/Issue/IssueDetail/index.js
  client/src/Components/Issue/SideBarList.js
  client/src/Context/IssueInfoContext.js
Labels: frontend 🎨, web

#251 [Feat/title#236] 이슈 타이틀 변경 기능 구현
  client/src/Components/Issue/IssueDetail/Button.js
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueDetail/IssueDetailHeader.js
  client/src/Components/Issue/IssueDetail/IssueTitle.js
  client/src/Components/Issue/IssueDetail/IssueTitleEditor.js
  client/src/theme.js
Labels: frontend 🎨

#253 [Bug/#232] Label & milestone 클릭 button 색 변경
  client/src/Components/Common/LabelButton.js
  client/src/Components/Common/LabelMilestoneButton.js
  client/src/Components/Common/MilestoneButton.js
  client/src/Components/Issue/Issue.js
  client/src/Components/Label/Label.js
  client/src/Components/Milestone/Milestone.js
  client/src/Components/Milestone/MilestoneEdit/MilestoneUpdateContainer.js
  client/src/Components/Milestone/MilestoneEdit/MilestoneUpdatePresenter.js
Labels: bug 🤔, frontend 🎨, web

#254 [Bug/#245] Resolve an issue where page movement not working
  client/src/Components/Milestone/MilestoneListRow.js
Labels: bug 🤔, frontend 🎨, web

#260 [Bug/#191] Label id를 변경 할 수 없는 bug
  client/src/Components/Label/LabelCreateModal/LabelCreateModalContainer.js
Labels: bug 🤔, frontend 🎨, web

#261 [Feat/vibe#259] 이슈디테일뷰에서 레이블 편집(추가)할때 진동 피드백 만들기
  iOS/IssueTracker/IssueTracker/Issue/IssueDetail/View/LabelEditCollectionViewCell.swift
Labels: 🍎 iOS 🍎

#269 [Feat/logout#267] Add logout icon & component
  client/src/Components/Common/Logout.js
  client/src/Components/static/svgIcons.js
Labels: frontend 🎨, web

#263 [Feat/update comment#248] 커멘트 수정 기능 추가
  client/src/Components/Issue/InputComment.js
  client/src/Components/Issue/IssueDetail/CommentEditor.js
  client/src/Components/Issue/IssueDetail/CommentList.js
  client/src/Components/Issue/IssueDetail/IssueComment.js
  client/src/Components/Issue/IssueDetail/index.js
  server/models/comment.js
Labels: frontend 🎨, web

#258 [Feat/md#252] 마크다운 렌더링
  client/package-lock.json
  client/package.json
  client/src/Components/Issue/InputComment.js
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueDetail/IssueComment.js
  client/src/Components/Issue/IssueDetail/Markdown.js
  client/src/Components/Issue/IssueDetail/index.js
  client/webpack.config.js
Labels: frontend 🎨

#270 [Feat/update issue state#247] 이슈 상태 변경 이벤트 추가
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Context/IssueInfoContext.js
Labels: frontend 🎨, web

#275 [Bug/#262] Token 없을 때 bug, api 성공 실패 여부 확인 메시지 띄우기
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Common/LabelButton.js
  client/src/Components/Common/MilestoneButton.js
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueDetail/IssueTitleEditor.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Components/Issue/NewIssue.js
  client/src/Components/Issue/NewIssueInput.js
  client/src/Components/Label/Label.js
  client/src/Components/Label/LabelCreateModal/LabelCreateModalContainer.js
  client/src/Components/Label/LabelList.js
  client/src/Components/Label/LabelListRow.js
  client/src/Components/Label/Search.js
  client/src/Components/Milestone/Milestone.js
  client/src/Components/Milestone/MilestoneCreate/MilestoneCreateContainer.js
  client/src/Components/Milestone/MilestoneEdit/MilestoneUpdateContainer.js
  client/src/Components/Milestone/MilestoneListRow.js
Labels: bug 🤔, frontend 🎨, web

#273 [Feat/logout#106] 로그아웃 기능 구현
  client/src/Components/Common/Header.js
  client/src/Context/AuthContext.js
  client/src/Routes/Authenticated.js
  client/src/Routes/index.js
  client/src/utils/cookie.js
Labels: frontend 🎨

#277 [Bug/#276] Fix label low & label filter render
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Components/Label/LabelListRow.js
Labels: bug 🤔, frontend 🎨, web

#274 [Fix/bug#271] 커멘트 생성 후, 이슈 상세 페이지가 재렌더링 되지 않는 오류 수정
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueDetail/CommentList.js
  client/src/Components/Issue/IssueDetail/index.js
  client/src/Context/IssueInfoContext.js
Labels: bug 🤔, frontend 🎨, web

#279 [Bug/#278] Update 된 내용이 바로 반영안되는 문제 해결
  client/src/Components/Milestone/MilestoneEdit/MilestoneUpdateContainer.js
Labels: bug 🤔, frontend 🎨, web

#281 [Fix/bug#280] 자잘한 오류 수정
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/IssueDetail/CommentList.js
  client/src/Components/Issue/IssueDetail/IssueComment.js
  client/src/Components/Issue/IssueLabel.js
Labels: bug 🤔, frontend 🎨, web

#287 [Fix/bug#286] 커멘트 개수 변경 안되는 오류 수정
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Context/IssueInfoContext.js
Labels: bug 🤔, frontend 🎨, web

#288 [Bug/color for dark mode] 다크모드 색상 지원
  iOS/IssueTracker/IssueTracker/Assets.xcassets/CloseColor.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/LabelCellColor.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/OpenColor.colorset/Contents.json
Labels: bug 🤔, 🍎 iOS 🍎

#289 [Fix/unknown] 아바타 깨지는 문제
  client/src/Components/Common/Unknown.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
Labels: bug 🤔

#290 버그 수정 후 웹 배포
  client/src/Components/Common/Unknown.js
  client/src/Components/Issue/CheckedList.js
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
  client/src/Context/IssueInfoContext.js
Labels: prod server ☁️

#292 자잘한 버그 수정 후 재배포
  client/src/Components/Issue/IssueDetail/CommentInput.js
  client/src/Components/Issue/IssueFilter/IssueFilterRender.js
Labels: prod server ☁️

#293 [fix/MileStone#291] MileStone Progress Percentage Error
  iOS/IssueTracker/IssueTracker/Issue/IssueList/IssueFilter/Filter.swift
  iOS/IssueTracker/IssueTracker/MileStone/MileStoneCollectionViewCell.swift
Labels: bug 🤔, 🍎 iOS 🍎
